INSERT INTO pais (id, nombre) VALUES('AF', 'Afghanistan');
INSERT INTO pais (id, nombre) VALUES('AL', 'Albania');
INSERT INTO pais (id, nombre) VALUES('DZ', 'Algeria');
INSERT INTO pais (id, nombre) VALUES('AD', 'Andorra');
INSERT INTO pais (id, nombre) VALUES('AO', 'Angola');
INSERT INTO pais (id, nombre) VALUES('AG', 'Antigua and Barbuda');
INSERT INTO pais (id, nombre) VALUES('AR', 'Argentina');
INSERT INTO pais (id, nombre) VALUES('AM', 'Armenia');
INSERT INTO pais (id, nombre) VALUES('AU', 'Australia');
INSERT INTO pais (id, nombre) VALUES('AT', 'Austria');
INSERT INTO pais (id, nombre) VALUES('AZ', 'Azerbaijan');
INSERT INTO pais (id, nombre) VALUES('BH', 'Bahrain');
INSERT INTO pais (id, nombre) VALUES('BD', 'Bangladesh');
INSERT INTO pais (id, nombre) VALUES('BB', 'Barbados');
INSERT INTO pais (id, nombre) VALUES('BY', 'Belarus');
INSERT INTO pais (id, nombre) VALUES('BE', 'Belgium');
INSERT INTO pais (id, nombre) VALUES('BZ', 'Belize');
INSERT INTO pais (id, nombre) VALUES('BJ', 'Benin');
INSERT INTO pais (id, nombre) VALUES('BT', 'Bhutan');
INSERT INTO pais (id, nombre) VALUES('BO', 'Bolivia');
INSERT INTO pais (id, nombre) VALUES('BA', 'Bosnia and Herzegovina');
INSERT INTO pais (id, nombre) VALUES('BW', 'Botswana');
INSERT INTO pais (id, nombre) VALUES('BR', 'Brazil');
INSERT INTO pais (id, nombre) VALUES('BN', 'Brunei');
INSERT INTO pais (id, nombre) VALUES('BG', 'Bulgaria');
INSERT INTO pais (id, nombre) VALUES('BF', 'Burkina Faso');
INSERT INTO pais (id, nombre) VALUES('BI', 'Burundi');
INSERT INTO pais (id, nombre) VALUES('KH', 'Cambodia');
INSERT INTO pais (id, nombre) VALUES('CM', 'Cameroon');
INSERT INTO pais (id, nombre) VALUES('CA', 'Canada');
INSERT INTO pais (id, nombre) VALUES('CV', 'Cape Verde');
INSERT INTO pais (id, nombre) VALUES('CF', 'Central African Republic');
INSERT INTO pais (id, nombre) VALUES('TD', 'Chad');
INSERT INTO pais (id, nombre) VALUES('CL', 'Chile');
INSERT INTO pais (id, nombre) VALUES('CN', 'China');
INSERT INTO pais (id, nombre) VALUES('CO', 'Colombia');
INSERT INTO pais (id, nombre) VALUES('KM', 'Comoros');
INSERT INTO pais (id, nombre) VALUES('CG', 'Congo');
INSERT INTO pais (id, nombre) VALUES('CD', 'Congo, Democratic Republic of the');
INSERT INTO pais (id, nombre) VALUES('CR', 'Costa Rica');
INSERT INTO pais (id, nombre) VALUES('HR', 'Croatia');
INSERT INTO pais (id, nombre) VALUES('CU', 'Cuba');
INSERT INTO pais (id, nombre) VALUES('CY', 'Cyprus');
INSERT INTO pais (id, nombre) VALUES('CZ', 'Czech Republic');
INSERT INTO pais (id, nombre) VALUES('DK', 'Denmark');
INSERT INTO pais (id, nombre) VALUES('DJ', 'Djibouti');
INSERT INTO pais (id, nombre) VALUES('DM', 'Dominica');
INSERT INTO pais (id, nombre) VALUES('DO', 'Dominican Republic');
INSERT INTO pais (id, nombre) VALUES('EC', 'Ecuador');
INSERT INTO pais (id, nombre) VALUES('EG', 'Egypt');
INSERT INTO pais (id, nombre) VALUES('SV', 'El Salvador');
INSERT INTO pais (id, nombre) VALUES('GQ', 'Equatorial Guinea');
INSERT INTO pais (id, nombre) VALUES('ER', 'Eritrea');
INSERT INTO pais (id, nombre) VALUES('EE', 'Estonia');
INSERT INTO pais (id, nombre) VALUES('SZ', 'Eswatini');
INSERT INTO pais (id, nombre) VALUES('ET', 'Ethiopia');
INSERT INTO pais (id, nombre) VALUES('FJ', 'Fiji');
INSERT INTO pais (id, nombre) VALUES('FI', 'Finland');
INSERT INTO pais (id, nombre) VALUES('FR', 'France');
INSERT INTO pais (id, nombre) VALUES('GA', 'Gabon');
INSERT INTO pais (id, nombre) VALUES('GM', 'Gambia');
INSERT INTO pais (id, nombre) VALUES('GE', 'Georgia');
INSERT INTO pais (id, nombre) VALUES('DE', 'Germany');
INSERT INTO pais (id, nombre) VALUES('GH', 'Ghana');
INSERT INTO pais (id, nombre) VALUES('GR', 'Greece');
INSERT INTO pais (id, nombre) VALUES('GD', 'Grenada');
INSERT INTO pais (id, nombre) VALUES('GT', 'Guatemala');
INSERT INTO pais (id, nombre) VALUES('GN', 'Guinea');
INSERT INTO pais (id, nombre) VALUES('GW', 'Guinea-Bissau');
INSERT INTO pais (id, nombre) VALUES('GY', 'Guyana');
INSERT INTO pais (id, nombre) VALUES('HT', 'Haiti');
INSERT INTO pais (id, nombre) VALUES('HN', 'Honduras');
INSERT INTO pais (id, nombre) VALUES('HU', 'Hungary');
INSERT INTO pais (id, nombre) VALUES('IS', 'Iceland');
INSERT INTO pais (id, nombre) VALUES('IN', 'India');
INSERT INTO pais (id, nombre) VALUES('ID', 'Indonesia');
INSERT INTO pais (id, nombre) VALUES('IR', 'Iran');
INSERT INTO pais (id, nombre) VALUES('IQ', 'Iraq');
INSERT INTO pais (id, nombre) VALUES('IE', 'Ireland');
INSERT INTO pais (id, nombre) VALUES('IL', 'Israel');
INSERT INTO pais (id, nombre) VALUES('IT', 'Italy');
INSERT INTO pais (id, nombre) VALUES('CI', 'Ivory Coast (Côte d''Ivoire)');
INSERT INTO pais (id, nombre) VALUES('JM', 'Jamaica');
INSERT INTO pais (id, nombre) VALUES('JP', 'Japan');
INSERT INTO pais (id, nombre) VALUES('JO', 'Jordan');
INSERT INTO pais (id, nombre) VALUES('KZ', 'Kazakhstan');
INSERT INTO pais (id, nombre) VALUES('KE', 'Kenya');
INSERT INTO pais (id, nombre) VALUES('KI', 'Kiribati');
INSERT INTO pais (id, nombre) VALUES('KO', 'Kosove');
INSERT INTO pais (id, nombre) VALUES('KW', 'Kuwait');
INSERT INTO pais (id, nombre) VALUES('KG', 'Kyrgyzstan');
INSERT INTO pais (id, nombre) VALUES('LA', 'Laos');
INSERT INTO pais (id, nombre) VALUES('LV', 'Latvia');
INSERT INTO pais (id, nombre) VALUES('LB', 'Lebanon');
INSERT INTO pais (id, nombre) VALUES('LS', 'Lesotho');
INSERT INTO pais (id, nombre) VALUES('LR', 'Liberia');
INSERT INTO pais (id, nombre) VALUES('LY', 'Libya');
INSERT INTO pais (id, nombre) VALUES('LI', 'Liechtenstein');
INSERT INTO pais (id, nombre) VALUES('LT', 'Lithuania');
INSERT INTO pais (id, nombre) VALUES('LU', 'Luxembourg');
INSERT INTO pais (id, nombre) VALUES('MG', 'Madagascar');
INSERT INTO pais (id, nombre) VALUES('MW', 'Malawi');
INSERT INTO pais (id, nombre) VALUES('MY', 'Malaysia');
INSERT INTO pais (id, nombre) VALUES('MV', 'Maldives');
INSERT INTO pais (id, nombre) VALUES('ML', 'Mali');
INSERT INTO pais (id, nombre) VALUES('MT', 'Malta');
INSERT INTO pais (id, nombre) VALUES('MH', 'Marshall Islands');
INSERT INTO pais (id, nombre) VALUES('MR', 'Mauritania');
INSERT INTO pais (id, nombre) VALUES('MU', 'Mauritius');
INSERT INTO pais (id, nombre) VALUES('MX', 'Mexico');
INSERT INTO pais (id, nombre) VALUES('FM', 'Micronesia (Federated States of)');
INSERT INTO pais (id, nombre) VALUES('MD', 'Moldova');
INSERT INTO pais (id, nombre) VALUES('MC', 'Monaco');
INSERT INTO pais (id, nombre) VALUES('MN', 'Mongolia');
INSERT INTO pais (id, nombre) VALUES('ME', 'Montenegro');
INSERT INTO pais (id, nombre) VALUES('MA', 'Morocco');
INSERT INTO pais (id, nombre) VALUES('MZ', 'Mozambique');
INSERT INTO pais (id, nombre) VALUES('MM', 'Myanmar');
INSERT INTO pais (id, nombre) VALUES('NA', 'Namibia');
INSERT INTO pais (id, nombre) VALUES('NR', 'Nauru');
INSERT INTO pais (id, nombre) VALUES('NP', 'Nepal');
INSERT INTO pais (id, nombre) VALUES('NL', 'Netherlands');
INSERT INTO pais (id, nombre) VALUES('NZ', 'New Zealand');
INSERT INTO pais (id, nombre) VALUES('NI', 'Nicaragua');
INSERT INTO pais (id, nombre) VALUES('NE', 'Niger');
INSERT INTO pais (id, nombre) VALUES('NG', 'Nigeria');
INSERT INTO pais (id, nombre) VALUES('KP', 'North Korea');
INSERT INTO pais (id, nombre) VALUES('MK', 'North Macedonia');
INSERT INTO pais (id, nombre) VALUES('NO', 'Norway');
INSERT INTO pais (id, nombre) VALUES('OM', 'Oman');
INSERT INTO pais (id, nombre) VALUES('PK', 'Pakistan');
INSERT INTO pais (id, nombre) VALUES('PW', 'Palau');
INSERT INTO pais (id, nombre) VALUES('PA', 'Panama');
INSERT INTO pais (id, nombre) VALUES('PG', 'Papua New Guinea');
INSERT INTO pais (id, nombre) VALUES('PY', 'Paraguay');
INSERT INTO pais (id, nombre) VALUES('PE', 'Peru');
INSERT INTO pais (id, nombre) VALUES('PH', 'Philippines');
INSERT INTO pais (id, nombre) VALUES('PL', 'Poland');
INSERT INTO pais (id, nombre) VALUES('PT', 'Portugal');
INSERT INTO pais (id, nombre) VALUES('QA', 'Qatar');
INSERT INTO pais (id, nombre) VALUES('RO', 'Romania');
INSERT INTO pais (id, nombre) VALUES('RU', 'Russia');
INSERT INTO pais (id, nombre) VALUES('RW', 'Rwanda');
INSERT INTO pais (id, nombre) VALUES('KN', 'Saint Kitts and Nevis');
INSERT INTO pais (id, nombre) VALUES('LC', 'Saint Lucia');
INSERT INTO pais (id, nombre) VALUES('VC', 'Saint Vincent and the Grenadines');
INSERT INTO pais (id, nombre) VALUES('WS', 'Samoa');
INSERT INTO pais (id, nombre) VALUES('SM', 'San Marino');
INSERT INTO pais (id, nombre) VALUES('ST', 'Sao Tome and Principe');
INSERT INTO pais (id, nombre) VALUES('SA', 'Saudi Arabia');
INSERT INTO pais (id, nombre) VALUES('SN', 'Senegal');
INSERT INTO pais (id, nombre) VALUES('RS', 'Serbia');
INSERT INTO pais (id, nombre) VALUES('SC', 'Seychelles');
INSERT INTO pais (id, nombre) VALUES('SL', 'Sierra Leone');
INSERT INTO pais (id, nombre) VALUES('SG', 'Singapore');
INSERT INTO pais (id, nombre) VALUES('SK', 'Slovakia');
INSERT INTO pais (id, nombre) VALUES('SI', 'Slovenia');
INSERT INTO pais (id, nombre) VALUES('SB', 'Solomon Islands');
INSERT INTO pais (id, nombre) VALUES('SO', 'Somalia');
INSERT INTO pais (id, nombre) VALUES('ZA', 'South Africa');
INSERT INTO pais (id, nombre) VALUES('KR', 'South Korea');
INSERT INTO pais (id, nombre) VALUES('SS', 'South Sudan');
INSERT INTO pais (id, nombre) VALUES('ES', 'Spain');
INSERT INTO pais (id, nombre) VALUES('LK', 'Sri Lanka');
INSERT INTO pais (id, nombre) VALUES('SD', 'Sudan');
INSERT INTO pais (id, nombre) VALUES('SR', 'Suriname');
INSERT INTO pais (id, nombre) VALUES('SE', 'Sweden');
INSERT INTO pais (id, nombre) VALUES('CH', 'Switzerland');
INSERT INTO pais (id, nombre) VALUES('SY', 'Syria');
INSERT INTO pais (id, nombre) VALUES('TJ', 'Tajikistan');
INSERT INTO pais (id, nombre) VALUES('TZ', 'Tanzania');
INSERT INTO pais (id, nombre) VALUES('TH', 'Thailand');
INSERT INTO pais (id, nombre) VALUES('BS', 'The Bahamas');
INSERT INTO pais (id, nombre) VALUES('TL', 'Timor-Leste');
INSERT INTO pais (id, nombre) VALUES('TG', 'Togo');
INSERT INTO pais (id, nombre) VALUES('TO', 'Tonga');
INSERT INTO pais (id, nombre) VALUES('TT', 'Trinidad and Tobago');
INSERT INTO pais (id, nombre) VALUES('TN', 'Tunisia');
INSERT INTO pais (id, nombre) VALUES('TR', 'Turkey');
INSERT INTO pais (id, nombre) VALUES('TM', 'Turkmenistan');
INSERT INTO pais (id, nombre) VALUES('TV', 'Tuvalu');
INSERT INTO pais (id, nombre) VALUES('UG', 'Uganda');
INSERT INTO pais (id, nombre) VALUES('UA', 'Ukraine');
INSERT INTO pais (id, nombre) VALUES('AE', 'United Arab Emirates');
INSERT INTO pais (id, nombre) VALUES('GB', 'United Kingdom');
INSERT INTO pais (id, nombre) VALUES('US', 'United States of America');
INSERT INTO pais (id, nombre) VALUES('UY', 'Uruguay');
INSERT INTO pais (id, nombre) VALUES('UZ', 'Uzbekistan');
INSERT INTO pais (id, nombre) VALUES('VU', 'Vanuatu');
INSERT INTO pais (id, nombre) VALUES('VA', 'Vatican (Holy See)');
INSERT INTO pais (id, nombre) VALUES('VE', 'Venezuela');
INSERT INTO pais (id, nombre) VALUES('VN', 'Vietnam');
INSERT INTO pais (id, nombre) VALUES('YE', 'Yemen');
INSERT INTO pais (id, nombre) VALUES('ZM', 'Zambia');
INSERT INTO pais (id, nombre) VALUES('ZW', 'Zimbabwe');

