CREATE TABLE IF NOT EXISTS pais (
  id VARCHAR(2) PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL
);

CREATE TABLE persona (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombres VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    pais VARCHAR(255) NOT NULL
);
