CREATE TABLE IF NOT EXISTS pais (
  id VARCHAR(2) PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS persona (
  id INT PRIMARY KEY,
  nombres VARCHAR(255) NOT NULL,
  apellidos VARCHAR(255) NOT NULL,
  pais VARCHAR(255) NOT NULL,
  FOREIGN KEY (pais) REFERENCES pais(id)
);